#!/bin/bash

#python test.py -i "/media/mohammed/Drive_full_of_surprises/Projects/Dataset/Image_Tiles/1237/part2" \
#-gt "/media/mohammed/Drive_full_of_surprises/Projects/Dataset/ground_truth/density_map/part2" \
#-l "/home/mohammed/tf_logs"


#python refined_train.py -i "/media/mohammed/Drive_full_of_surprises/Projects/Dataset/Image_Tiles/1237/part2" \
#-gt "/media/mohammed/Drive_full_of_surprises/Projects/Dataset/ground_truth/density_map/part2" \
#-l "/home/mohammed/tf_logs" \
#-ckpt_path "/home/mohammed/tf_ckpt"

python refined_train.py -i "/media/mohammed/Drive_full_of_surprises/Projects/Dataset/Image_Tiles/1109" \
-gt "/media/mohammed/Drive_full_of_surprises/Projects/Dataset/ground_truth/density_map/1109" \
-l "/home/mohammed/tf_logs" \
-ckpt_path "/home/mohammed/tf_ckpt"



#python refined_test.py -i "/media/mohammed/Drive_full_of_surprises/Projects/Dataset/Image_Tiles/1237/part2" \
#-gt "/media/mohammed/Drive_full_of_surprises/Projects/Dataset/ground_truth/density_map/part2" \
#-l "/home/mohammed/tf_logs" \
#-ckpt_path "/home/mohammed/tf_ckpt"


#python show_predicted_map.py -i "/media/mohammed/Drive_full_of_surprises/Projects/Dataset/Image_Tiles/1237/part2/prediction_test" \
#-gt "/media/mohammed/Drive_full_of_surprises/Projects/Dataset/ground_truth/density_map/part2/prediction_test" \
#-l "/home/mohammed/tf_logs" \
#-ckpt_path "/home/mohammed/tf_ckpt"


